version: '3.3'
services:
  db:
    image: kartoza/postgis:11.0-2.5 # PreBuilt Docker Image Containing PostGIS
    volumes:
      - /docker/storage/postgis:/var/lib/postgresql #Mounting the folder Containing the Database Files to the Local System.
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=${sqlUser} #Values will be substituted by the Environment Variable sqlUser
      - POSTGRES_PASS=${sqlPass}
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,ogr_fdw
    ports:
      - 5432:5432 #Binds port 5432 in the Docker Container to that on the local System
    restart: on-failure