version: '3.3'

services:

  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - /docker/storage/postifs:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=${sqlUser}
      - POSTGRES_PASS=${sqlPass}
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,ogr_fdw
    ports:
      - 5432:5432
    restart: on-failure