version: '3.9'
services:
  proxy:
    extends:
      file: ./proxy/docker-compose.yml
      service: traefik

  jelly:
    extends:
      file: ./jelly/docker-compose.yml
      service: jellyfin

  torrent:
    extends:
      file: ./rutorrent/docker-compose.yml
      service: rutorrent
  
  fastdl:
    extends:
      file: ./fastdl/docker-compose.yml
      service: fastdl

  squid:
    extends:
      file: ./squid/docker-compose.yml
      service: squid

  wordpress:
    file: ./wordpress/docker-compose.yml
    service: wordpress

networks:
  traefik-public:
    external: true