version: '3.9'
services:
  proxy:
    extends:
      file: ./proxy/docker-compose.yml
      service: traefik

  arthur_web:
    extends:
      file: ./arthurcoll.com/docker-compose.yml
      service: arthur_web

  jelly:
    extends:
      file: ./jelly/docker-compose.yml
      service: jellyfin

  torrent:
    extends:
      file: ./rutorrent/docker-compose.yml
      service: rutorrent
  
  fastdl:
    extends:
      file: ./fastdl/docker-compose.yml
      service: fastdl

  squid:
    extends:
      file: ./squid/docker-compose.yml
      service: squid

networks:
  traefik-public:
    external: true