version: '3.3'

services:
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    restart: always
    volumes:
      - /docker/r4/storage/bitwarden/data:/data
    environment:
      WEBSOCKET_ENABLED: "false"
      SIGNUPS_ALLOWED: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bitwarden-https.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden-http.entrypoints=web"
      - "traefik.http.routers.bitwarden-http.rule=Host(`bitwarden.r4.ie`)"
      - "traefik.http.routers.bitwarden-http.middlewares=bitwarden-https@docker"
      - "traefik.http.routers.bitwarden.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.r4.ie`)"
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.routers.bitwarden.tls.certresolver=default"
    networks:
     - traefik-public

networks:
  traefik-public:
    external: true

