version: '3.3'

services:
  bitwarden:
    image: bitwardenrs/server
    restart: always
    volumes:
      - /docker/r4/storage/bitwarden/data:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
    labels:
      - traefik.web.frontend.rule=Host:bitwarden.r4.ie
      - traefik.web.port=80
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
      - traefik.docker.network=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https
      - traefik.hub.frontend.rule=Host:bitwarden.r4.ie;Path:/notifications/hub
      - traefik.hub.port=3012
      - traefik.hub.protocol=ws
    networks:
     - traefik-public

networks:
  traefik-public:
    external: true

