version: '3.3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    deploy:
      labels:
        - traefik.frontend.rule=Host:plex.damocles.asia
        - traefik.enable=true
        - traefik.port=32400
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
    volumes:
      - /home/r4/docker/plex/config:/config
      - /home/r4/docker/plex/tv:/data/tvshows
      - /home/r4/docker/plex/movies:/data/movies
      - /home/r4/docker/plex/anime:/data/anime
      - /home/r4/docker/torrent/downloads:/data/torrents
      - /home/r4/docker/plex/transcode:/transcode
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
