version: '3.3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.plex-https.redirectscheme.scheme=https"
      - "traefik.http.routers.plex-http.entrypoints=web"
      - "traefik.http.routers.plex-http.rule=Host(`plex.damocles.asia`)"
      - "traefik.http.routers.plex-http.middlewares=plex-https@docker"
      - "traefik.http.routers.plex.entrypoints=web-secure"
      - "traefik.http.routers.plex.rule=Host(`plex.damocles.asia`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=default"
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
    volumes:
      - /home/r4/docker/plex/config:/config
      - /home/r4/docker:/data
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
