version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "CHANGE_ME"
    MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"
  panel:
    &panel-environment
    APP_URL: "https://panel1.r4.ie"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: library/mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    networks:
      - local

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    networks:
      - traefik-public
      - local
    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/conf.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/var/log/"
    environment:
      <<: *panel-environment
      <<: *mail-environment
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.panel-https.redirectscheme.scheme=https"
      - "traefik.http.routers.panel-http.entrypoints=web"
      - "traefik.http.routers.panel-http.rule=Host(`panel1.r4.ie`)"
      - "traefik.http.routers.panel-http.middlewares=panel-https@docker"
      - "traefik.http.routers.panel.entrypoints=web-secure"
      - "traefik.http.routers.panel.rule=Host(`panel1.r4.ie`)"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.certresolver=default"

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    networks:
      - wings0
      - traefik-public
    ports:
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC"
      DEBUG: "false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you user let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.node-https.redirectscheme.scheme=https"
      - "traefik.http.routers.node-http.entrypoints=web"
      - "traefik.http.routers.node-http.rule=Host(`node1.r4.ie`)"
      - "traefik.http.routers.node-http.middlewares=node-https@docker"
      - "traefik.http.routers.node.entrypoints=web-secure"
      - "traefik.http.routers.node.rule=Host(`node1.r4.ie`)"
      - "traefik.http.routers.node.tls=true"
      - "traefik.http.routers.node.tls.certresolver=default"
      - traefik.http.services.node.loadbalancer.server.port=8080

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
  traefik-public:
    external: true
  local:
    internal: true