version: '3.3'
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - net
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.swarmpit-https.redirectscheme.scheme=https"
      - "traefik.http.routers.swarmpit-http.entrypoints=web"
      - "traefik.http.routers.swarmpit-http.rule=Host(`swarmpit.r4.ie`)"
      - "traefik.http.routers.swarmpit-http.middlewares=swarmpit-https@docker"
      - "traefik.http.routers.swarmpit.entrypoints=web-secure"
      - "traefik.http.routers.swarmpit.rule=Host(`swarmpit.r4.ie`)"
      - "traefik.http.routers.swarmpit.tls=true"
      - "traefik.http.routers.swarmpit.tls.certresolver=default"
      
  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
  
networks:
  net:
    internal: true
  traefik-public:
    external: true

volumes:
  db-data:
    driver: local
