version: '2'

services:
  nextcloud:
    image: linuxserver/nextcloud
    restart: unless-stopped
    environment:
      PUID:
      PGID:
    ports:
      - 443:443
    volumes:
     - /home/kingr4/nextcloud:/data
     - /home/kingr4/nextcloudconfig:/config
