version: '3.3'
services:
  arthur_web:
    image: httpd
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.app-https.redirectscheme.scheme=https"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.rule=Host(`app.r4.ie`)"
      - "traefik.http.routers.app-http.middlewares=app-https@docker"
      - "traefik.http.routers.app.entrypoints=web-secure"
      - "traefik.http.routers.app.rule=Host(`app.r4.ie`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=default"
    volumes:
     - /docker/r4/storage/discount:/usr/local/apache2/htdocs/
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
