version: '3.3'

services:
  pgadmin:
    image: dpage/pgadmin4
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.pgadmin-https.redirectscheme.scheme=https"
      - "traefik.http.routers.pgadmin-http.entrypoints=web"
      - "traefik.http.routers.pgadmin-http.rule=Host(`pg.r4.ie`)"
      - "traefik.http.routers.pgadmin-http.middlewares=pgadmin-https@docker"
      - "traefik.http.routers.pgadmin.entrypoints=web-secure"
      - "traefik.http.routers.pgadmin.rule=Host(`pg.r4.ie`)"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=default"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
        - pgadmin:/var/lib/pgadmin
    networks:
     - traefik-public

networks:
  traefik-public:
    external: true

volumes:
    pgadmin: 