version: '3.3'
services:
  znc:
    image: linuxserver/znc
    container_name: znc
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.znc-https.redirectscheme.scheme=https"
      - "traefik.http.routers.znc-http.entrypoints=web"
      - "traefik.http.routers.znc-http.rule=Host(`znc2.r4.ie`)"
      - "traefik.http.routers.znc-http.middlewares=znc-https@docker"
      - "traefik.http.routers.znc.entrypoints=web-secure"
      - "traefik.http.routers.znc.rule=Host(`znc2.r4.ie`)"
      - "traefik.http.routers.znc.tls=true"
      - "traefik.http.routers.znc.tls.certresolver=default"
      - traefik.http.services.znc.loadbalancer.server.port=6501
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
    volumes:
      - /home/r4/docker/znc/config:/config
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true