version: '3.3'
services:
  tf2:
    image: cm2network/tf2:sourcemod
    container_name: tf2
    restart: always
    network_mode: "host"
    environment:
      SRCDS_TOKEN: "BEDA2B9494A641083421C314A8C33457"
      SRCDS_STARTMAP: "koth_airfield_b7"
      SRCDS_MAXPLAYERS: 32
    volumes:
      - /docker/storage/tf2:/home/steam/tf-dedicated/
