version: '3.3'
services:
  bics:
    image: httpd
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bics-https.redirectscheme.scheme=https"
      - "traefik.http.routers.bics-http.entrypoints=web"
      - "traefik.http.routers.bics-http.rule=Host(`bics.r4.ie`)"
      - "traefik.http.routers.bics-http.middlewares=bics-https@docker"
      - "traefik.http.routers.bics.entrypoints=web-secure"
      - "traefik.http.routers.bics.rule=Host(`bics.r4.ie`)"
      - "traefik.http.routers.bics.tls=true"
      - "traefik.http.routers.bics.tls.certresolver=default"
    volumes:
      - /docker/storage/NetSoc.dit.ie/Comp-Web/bics/public:/usr/local/apache2/htdocs/
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
  traefik:
    internal: true