version: '3.9'

services:
  wordpress:
    image: wordpress
    restart: always
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.scouts-https.redirectscheme.scheme=https"
      - "traefik.http.routers.scouts-http.entrypoints=web"
      - "traefik.http.routers.scouts-http.rule=Host(`3rdscouts.ie`)"
      - "traefik.http.routers.scouts-http.middlewares=scouts-https@docker"
      - "traefik.http.routers.scouts.entrypoints=web-secure"
      - "traefik.http.routers.scouts.rule=Host(`3rdscouts.ie`)"
      - "traefik.http.routers.scouts.tls=true"
      - "traefik.http.routers.scouts.tls.certresolver=default"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=scouts
    volumes:
      - /docker/scouts/web:/var/www/html
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini:z
    networks:
      - traefik-public
      - scout

  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: scouts
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /docker/scouts/db:/var/lib/mysql
    networks:
      - scout

networks:
  traefik-public:
    external: true