version: '3.3'

services:
  wp_main:
    image: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.personal-https.redirectscheme.scheme=https"
      - "traefik.http.routers.personal-http.entrypoints=web"
      - "traefik.http.routers.personal-http.rule=Host(`shurikon.r4.ie`)"
      - "traefik.http.routers.personal-http.middlewares=personal-https@docker"
      - "traefik.http.routers.personal.entrypoints=web-secure"
      - "traefik.http.routers.personal.rule=Host(`shurikon.r4.ie`)"
      - "traefik.http.routers.personal.tls=true"
      - "traefik.http.routers.personal.tls.certresolver=default"
    depends_on:
      - wp_mysql
    environment:
      WORDPRESS_DB_HOST: wp_mysql
      WORDPRESS_DB_NAME: ${wpdb}
      WORDPRESS_DB_USER: ${sqluser}
      WORDPRESS_DB_PASSWORD: ${sqlpasswd}
    volumes:
     - /docker/r4/storage/shurikon/code:/code
     - /docker/r4/storage/shurikon/html/wp-content:/var/www/html/wp-content
     - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
     - traefik-public

  wp_mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${wpdb}
      MYSQL_USER: ${sqluser}
      MYSQL_PASSWORD: ${sqlpasswd}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /docker/r4/storage/shurikon/db:/var/lib/mysql
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
