version: '3.3'

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/certs/acme.json:/acme.json
      - ./traefik.toml:/traefik.toml
    labels:
    - "traefik.http.routers.api.rule=Host(`traefik.r4.ie`)"
    - "traefik.http.routers.api.entrypoints=web-secure"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.middlewares=myAuth"
    - "traefik.http.routers.api.tls"
    - "traefik.http.middlewares.myAuth.basicauth.users=test:$$2y$$10$$.OakivUMNHiQxvPwNaDyL.UpsEPkQZKztQ5m6HEHr6znk68yQVeAS"
    networks:
      - traefik-public
      - traefik


networks:
  traefik-public:
    external: true
  traefik:
    internal: true