 [http.routers.dmap]
      rule = "Host(`map.r4.ie`)"
      entrypoints = ["web-secure"]
      service = "dmap"
   [http.routers.dmap.tls]
      certResolver = "default"

[http.middlewares]
  [http.middlewares.dmap.redirectScheme]
    scheme = "https"
    permanent = true
 [http.services]
         [http.services.dmap.loadBalancer]
           [[http.services.dmap.loadBalancer.servers]]
             url = "http://192.168.10.1:8100"