   # Define a connection between requests and services
     [http.routers.dmap]
        rule = "Host(`map.r4.ie`)"
        entrypoints = ["web-secure"]
        service = "nas"
     [http.routers.dmap.tls]
        certResolver = "httpChallenge"


 [http.services]
        # Define how to reach an existing service on our infrastructure
        [http.services.dmap.loadBalancer]
           [[http.services.dmap.loadBalancer.servers]]
             url = "http://127.0.0.1:8123"