[log]
  level = "INFO"

[providers.docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik-public"

[api]
  dashboard = true
  debug = true

[providers.file]	
  filename = "./servers.toml"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.default.acme]
    email = "kingr4@protonmail.ch"
    storage = "acme.json"
  [certificatesResolvers.default.acme.httpChallenge]
    entryPoint = "web"
  
