[log]
  level = "ERROR"

[providers.docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"
  network = "traefik-public"

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.default.acme]
    email = "kingr4@protonmail.ch"
    storage = "acme.json"
  [certificatesResolvers.default.acme.httpChallenge]
    entryPoint = "web"
  
[backends]
[backends.dmap]
        [backends.dmap.servers.dmap]
            url = "http://127.0.0.1:8123"

[frontends]
        [frontends.domain]
                backend = "dmap"
        [frontends.domain.routes.domain]
                rule = "Host:map.r4.ie"