version: '3.3'
services:
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.torrent-https.redirectscheme.scheme=https"
      - "traefik.http.routers.torrent-http.entrypoints=web"
      - "traefik.http.routers.torrent-http.rule=Host(`torrent.damocles.asia`)"
      - "traefik.http.routers.torrent-http.middlewares=torrent-https@docker"
      - "traefik.http.routers.torrent.entrypoints=web-secure"
      - "traefik.http.routers.torrent.rule=Host(`torrent.damocles.asia`)"
      - "traefik.http.routers.torrent.tls=true"
      - "traefik.http.routers.torrent.tls.certresolver=default"
      - "traefik.http.routers.torrent.middlewares=myAuth"
      - "traefik.http.middlewares.myAuth.basicauth.users=r4:$$2y$$10$$7kP272D0MI8MoLSVDnmbAuP3176jLUsZ6omEv2.nGtSbtvzuxBW0G"
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
    volumes:
      - /home/r4/docker/torrent/config:/config
      - /home/r4/docker/downloads:/downloads
      - /home/r4/docker:/docker
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
