version: '2'
services:
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
      VIRTUAL_HOST: plex.damocles.asia
      LETSENCRYPT_HOST: plex.damocles.asia
      LETSENCRYPT_EMAIL: kingr4@protonmail.ch
    volumes:
      - /home/r4/docker/torrent/config:/config
      - /home/r4/docker/torrent/downloads:/downloads
    ports:
      - 80:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
