version: '3.3'
services:
  rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rutorrent
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.torrent-https.redirectscheme.scheme=https"
      - "traefik.http.routers.torrent-http.entrypoints=web"
      - "traefik.http.routers.torrent-http.rule=Host(`torrent.r4.ie`)"
      - "traefik.http.routers.torrent-http.middlewares=torrent-https@docker"
      - "traefik.http.routers.torrent.entrypoints=web-secure"
      - "traefik.http.routers.torrent.rule=Host(`torrent.r4.ie`)"
      - "traefik.http.routers.torrent.tls=true"
      - "traefik.http.routers.torrent.tls.certresolver=default"
      - "traefik.http.routers.torrent.middlewares=myAuth"
      - "traefik.http.middlewares.myAuth.basicauth.users=r4:$$2y$$10$$7kP272D0MI8MoLSVDnmbAuP3176jLUsZ6omEv2.nGtSbtvzuxBW0G"
      - traefik.http.services.node.loadbalancer.server.port=8080
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: docker
    ports:
      - 5000:50000
    env_file:
      - "rtorrent.env"
    volumes:
      - /docker/torrent:/data
      - /storage/downloads:/downloads
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true