version: '3.7'

services:

  mysql:
    image: mariadb:10.5
    container_name: paneldb
    restart: always
    networks:
      - local
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql

  panel:
    image: ccarney16/pterodactyl-panel:v1.1.1
    restart: always
    container_name: panel
    networks:
      - local
      - traefik-public
    env_file:
      - .env
    depends_on:
      - cache
    environment:
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${DATA_DIR}/panel:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.panel-https.redirectscheme.scheme=https"
      - "traefik.http.routers.panel-http.entrypoints=web"
      - "traefik.http.routers.panel-http.rule=Host(`panel.r4.ie`)"
      - "traefik.http.routers.panel-http.middlewares=panel-https@docker"
      - "traefik.http.routers.panel.entrypoints=web-secure"
      - "traefik.http.routers.panel.rule=Host(`panel.r4.ie`)"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.certresolver=default"

  cache:
    image: redis:alpine
    container_name: panelcache
    restart: always
    networks:
      - local



networks:
  traefik-public:
    external: true
  local:
    external: false