version: '3.5'
services:
  database:
    image: mariadb:10.4
    restart: always
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=${ROOTPASSWD}"
      - "MYSQL_DATABASE=${DB}"
      - "MYSQL_USER=${USER}"
      - "MYSQL_PASSWORD=${PASSWD}"
    networks:
      - backend

  cache:
    image: redis:alpine
    restart: always
    networks:
      - backend

  panel:
    image: quay.io/parkervcp/pterodactyl:release_v1.0.3
    restart: always
    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/conf.d/"
      - "/srv/pterodactyl/logs/:/var/log/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.panel-https.redirectscheme.scheme=https"
      - "traefik.http.routers.panel-http.entrypoints=web"
      - "traefik.http.routers.panel-http.rule=Host(`panel.r4.ie`)"
      - "traefik.http.routers.panel-http.middlewares=panel-https@docker"
      - "traefik.http.routers.panel.entrypoints=web-secure"
      - "traefik.http.routers.panel.rule=Host(`panel.r4.ie`)"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.certresolver=default"
    environment:
      ## These are defaults and should be left alone
      - "APP_ENV=production"
      - "APP_DEBUG=true"
      - "APP_THEME=pterodactyl"
      - "APP_CLEAR_TASKLOG=720"
      - "APP_DELETE_MINUTES=10"
      - "APP_ENVIRONMENT_ONLY=false"
      - "QUEUE_HIGH=high"
      - "QUEUE_STANDARD=standard"
      - "QUEUE_LOW=low"
      ## Cache settings
      - "CACHE_DRIVER=redis"
      - "SESSION_DRIVER=redis"
      - "QUEUE_DRIVER=redis"
      - "REDIS_HOST=cache"
      - "REDIS_PASSWORD=null"
      - "REDIS_PORT=6379"
      ## Domain settings
      - "APP_URL=https://panel.r4.ie" ## if you are running this behind a reverse proxy with ssl app_url needs to be https still. 
      ## Timezone settings
      - "APP_TIMEZONE=UTC" ## http://php.net/manual/en/timezones.php
      ## Service egg settings
      - "APP_SERVICE_AUTHOR=noreply@panel.r4.ie" ## this is the email that gets put on eggs you create
      ## Database settings
      ## These can be left alone. Only change if you know what you are doing.
      - "DB_HOST=database" 
      - "DB_PORT=3306"
      - "DB_DATABASE=${DB}"
      - "DB_USERNAME=${USER}"
      - "DB_PASSWORD=${PASSWD}"
      ## Email settings
      - "MAIL_FROM=noreply@panel.r4.ie"
      - "MAIL_DRIVER=smtp"
      - "MAIL_HOST=mail"
      - "MAIL_PORT=1025"
      - "MAIL_USERNAME=''"
      - "MAIL_PASSWORD=''"
      - "MAIL_ENCRYPTION=true"
    networks:
      - backend
      - traefik-public

networks:
  traefik-public:
    external: true
  backend:
    internal: true