version: '3.3'
services:
  arthur_web:
    image: httpd
    restart: always
    container_name: website
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.personal-https.redirectscheme.scheme=https"
      - "traefik.http.routers.personal-http.entrypoints=web"
      - "traefik.http.routers.personal-http.rule=Host(`arthurcoll.com`)"
      - "traefik.http.routers.personal-http.middlewares=personal-https@docker"
      - "traefik.http.routers.personal.entrypoints=web-secure"
      - "traefik.http.routers.personal.rule=Host(`arthurcoll.com`)"
      - "traefik.http.routers.personal.tls=true"
      - "traefik.http.routers.personal.tls.certresolver=default"
    volumes:
     - /docker/storage/arthurcoll.com:/usr/local/apache2/htdocs/
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
  traefik:
    internal: true
