version: '2'

services:
  arthur_web:
    image: httpd
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: arthurcoll.com
      LETSENCRYPT_HOST: arthurcoll.com
      LETSENCRYPT_EMAIL: arthur1coll@gmail.com
    volumes:
     - /docker/r4/storage/arthurcoll.com:/usr/local/apache2/htdocs/

networks:
  default:
    external:
      name: nginx-proxy
