version: '3'
networks:
  web:
    external: true
  internal:
    external: false

services:
  arthur_web:
    image: httpd
    restart: unless-stopped
    labels:
      - traefik.backend=blog
      - traefik.frontend.rule=Host:truesdale.ovh
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
    volumes:
     - /docker/r4/storage/arthurcoll.com:/usr/local/apache2/htdocs/
