version: '3'
services:
  arthur_web:
    image: httpd
    restart: unless-stopped
    labels:
      - traefik.backend=blog
      - traefik.frontend.rule=Host:truesdale.ovh
      - traefik.docker.network=web
      - traefik.port=80
    volumes:
     - /docker/r4/storage/arthurcoll.com:/usr/local/apache2/htdocs/
    networks:
     - web-tier
